version: '3.8'

services:
  web:
    build:
      context: ./Django
      dockerfile: Django.Dockerfile
    restart: always
    volumes:
      - ./docker_volumes/dj/static:/usr/src/app/static
      - ./docker_volumes/dj/media:/usr/src/app/media
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      WEB_PORT: ${WEB_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TO: ${EMAIL_TO}
      EMAIL_TOKEN_ACCESS: ${EMAIL_TOKEN_ACCESS}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./docker_volumes/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker_volumes/dj/static:/home/app/web/static
      - ./docker_volumes/dj/media:/home/app/web/media
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - web
  
  db:
    image: postgres:14.12-alpine3.20
    volumes:
      - ./docker_volumes/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
    expose:
      - 5432